version: '3.8'

services:
  web:
    stdin_open: true
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/usr/src/
    ports:
      - 3000:3000
    # depends_on:
    #   - web