version: '3.8'

services:
  web:
    stdin_open: true
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../src:/usr/src/src
      - ../public:/usr/src/public
      # - /usr/src/node_modules
    ports:
      - 3000:3000