version: '3.8'

services:
  web:
    stdin_open: true
    build:
      context: ../
      dockerfile: docker_prod/Dockerfile
      args: 
        - NODE_ENV=production
        - REACT_APP_SERVICE_URL=http://localhost:3000
    volumes:
      - ..:/usr/src/
      - /usr/src/node_modules
    ports:
      - 3000:80